//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Bhulekh_Agent {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DataSet1")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DataSet1 : global::System.Data.DataSet {
        
        private dsAnshAgentScrappedDataDataTable tabledsAnshAgentScrappedData;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public DataSet1() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected DataSet1(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dsAnshAgentScrappedData"] != null)) {
                    base.Tables.Add(new dsAnshAgentScrappedDataDataTable(ds.Tables["dsAnshAgentScrappedData"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dsAnshAgentScrappedDataDataTable dsAnshAgentScrappedData {
            get {
                return this.tabledsAnshAgentScrappedData;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dsAnshAgentScrappedData"] != null)) {
                    base.Tables.Add(new dsAnshAgentScrappedDataDataTable(ds.Tables["dsAnshAgentScrappedData"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledsAnshAgentScrappedData = ((dsAnshAgentScrappedDataDataTable)(base.Tables["dsAnshAgentScrappedData"]));
            if ((initTable == true)) {
                if ((this.tabledsAnshAgentScrappedData != null)) {
                    this.tabledsAnshAgentScrappedData.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSet1.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledsAnshAgentScrappedData = new dsAnshAgentScrappedDataDataTable();
            base.Tables.Add(this.tabledsAnshAgentScrappedData);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializedsAnshAgentScrappedData() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DataSet1 ds = new DataSet1();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void dsAnshAgentScrappedDataRowChangeEventHandler(object sender, dsAnshAgentScrappedDataRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dsAnshAgentScrappedDataDataTable : global::System.Data.TypedTableBase<dsAnshAgentScrappedDataRow> {
            
            private global::System.Data.DataColumn columnGram_Name;
            
            private global::System.Data.DataColumn columnPargana_Name;
            
            private global::System.Data.DataColumn columnTehsil_Name;
            
            private global::System.Data.DataColumn columnDistrict_Name;
            
            private global::System.Data.DataColumn columnFasli_Year;
            
            private global::System.Data.DataColumn columnBhag;
            
            private global::System.Data.DataColumn columnKhata_No;
            
            private global::System.Data.DataColumn columnKhatedar_Owner;
            
            private global::System.Data.DataColumn columnKhatedar_Name;
            
            private global::System.Data.DataColumn columnKhatedar_Father_Name;
            
            private global::System.Data.DataColumn columnKhatedar_Living_Place;
            
            private global::System.Data.DataColumn columnKhatedar_Aadhar_No;
            
            private global::System.Data.DataColumn columnBhukhand_Code;
            
            private global::System.Data.DataColumn columnGata_No;
            
            private global::System.Data.DataColumn columnBhukhandOrGata_Area;
            
            private global::System.Data.DataColumn columnKhatedar_Ansh_Area;
            
            private global::System.Data.DataColumn columnAadesh;
            
            private global::System.Data.DataColumn columnTippadi;
            
            private global::System.Data.DataColumn columnBhukhandOrGata_Total_Area;
            
            private global::System.Data.DataColumn columnKhatedar_Ansh_Total_Area;
            
            private global::System.Data.DataColumn columnTotal_Gata_Code;
            
            private global::System.Data.DataColumn columnCategory;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAnshAgentScrappedDataDataTable() {
                this.TableName = "dsAnshAgentScrappedData";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsAnshAgentScrappedDataDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected dsAnshAgentScrappedDataDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Gram_NameColumn {
                get {
                    return this.columnGram_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Pargana_NameColumn {
                get {
                    return this.columnPargana_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Tehsil_NameColumn {
                get {
                    return this.columnTehsil_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn District_NameColumn {
                get {
                    return this.columnDistrict_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Fasli_YearColumn {
                get {
                    return this.columnFasli_Year;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BhagColumn {
                get {
                    return this.columnBhag;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Khata_NoColumn {
                get {
                    return this.columnKhata_No;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Khatedar_OwnerColumn {
                get {
                    return this.columnKhatedar_Owner;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Khatedar_NameColumn {
                get {
                    return this.columnKhatedar_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Khatedar_Father_NameColumn {
                get {
                    return this.columnKhatedar_Father_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Khatedar_Living_PlaceColumn {
                get {
                    return this.columnKhatedar_Living_Place;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Khatedar_Aadhar_NoColumn {
                get {
                    return this.columnKhatedar_Aadhar_No;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Bhukhand_CodeColumn {
                get {
                    return this.columnBhukhand_Code;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Gata_NoColumn {
                get {
                    return this.columnGata_No;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BhukhandOrGata_AreaColumn {
                get {
                    return this.columnBhukhandOrGata_Area;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Khatedar_Ansh_AreaColumn {
                get {
                    return this.columnKhatedar_Ansh_Area;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AadeshColumn {
                get {
                    return this.columnAadesh;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TippadiColumn {
                get {
                    return this.columnTippadi;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BhukhandOrGata_Total_AreaColumn {
                get {
                    return this.columnBhukhandOrGata_Total_Area;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Khatedar_Ansh_Total_AreaColumn {
                get {
                    return this.columnKhatedar_Ansh_Total_Area;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Total_Gata_CodeColumn {
                get {
                    return this.columnTotal_Gata_Code;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CategoryColumn {
                get {
                    return this.columnCategory;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAnshAgentScrappedDataRow this[int index] {
                get {
                    return ((dsAnshAgentScrappedDataRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsAnshAgentScrappedDataRowChangeEventHandler dsAnshAgentScrappedDataRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsAnshAgentScrappedDataRowChangeEventHandler dsAnshAgentScrappedDataRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsAnshAgentScrappedDataRowChangeEventHandler dsAnshAgentScrappedDataRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsAnshAgentScrappedDataRowChangeEventHandler dsAnshAgentScrappedDataRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AdddsAnshAgentScrappedDataRow(dsAnshAgentScrappedDataRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAnshAgentScrappedDataRow AdddsAnshAgentScrappedDataRow(
                        string Gram_Name, 
                        string Pargana_Name, 
                        string Tehsil_Name, 
                        string District_Name, 
                        string Fasli_Year, 
                        string Bhag, 
                        string Khata_No, 
                        string Khatedar_Owner, 
                        string Khatedar_Name, 
                        string Khatedar_Father_Name, 
                        string Khatedar_Living_Place, 
                        string Khatedar_Aadhar_No, 
                        string Bhukhand_Code, 
                        string Gata_No, 
                        string BhukhandOrGata_Area, 
                        string Khatedar_Ansh_Area, 
                        string Aadesh, 
                        string Tippadi, 
                        string BhukhandOrGata_Total_Area, 
                        string Khatedar_Ansh_Total_Area, 
                        string Total_Gata_Code, 
                        string Category) {
                dsAnshAgentScrappedDataRow rowdsAnshAgentScrappedDataRow = ((dsAnshAgentScrappedDataRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Gram_Name,
                        Pargana_Name,
                        Tehsil_Name,
                        District_Name,
                        Fasli_Year,
                        Bhag,
                        Khata_No,
                        Khatedar_Owner,
                        Khatedar_Name,
                        Khatedar_Father_Name,
                        Khatedar_Living_Place,
                        Khatedar_Aadhar_No,
                        Bhukhand_Code,
                        Gata_No,
                        BhukhandOrGata_Area,
                        Khatedar_Ansh_Area,
                        Aadesh,
                        Tippadi,
                        BhukhandOrGata_Total_Area,
                        Khatedar_Ansh_Total_Area,
                        Total_Gata_Code,
                        Category};
                rowdsAnshAgentScrappedDataRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdsAnshAgentScrappedDataRow);
                return rowdsAnshAgentScrappedDataRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dsAnshAgentScrappedDataDataTable cln = ((dsAnshAgentScrappedDataDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dsAnshAgentScrappedDataDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnGram_Name = base.Columns["Gram_Name"];
                this.columnPargana_Name = base.Columns["Pargana_Name"];
                this.columnTehsil_Name = base.Columns["Tehsil_Name"];
                this.columnDistrict_Name = base.Columns["District_Name"];
                this.columnFasli_Year = base.Columns["Fasli_Year"];
                this.columnBhag = base.Columns["Bhag"];
                this.columnKhata_No = base.Columns["Khata_No"];
                this.columnKhatedar_Owner = base.Columns["Khatedar_Owner"];
                this.columnKhatedar_Name = base.Columns["Khatedar_Name"];
                this.columnKhatedar_Father_Name = base.Columns["Khatedar_Father_Name"];
                this.columnKhatedar_Living_Place = base.Columns["Khatedar_Living_Place"];
                this.columnKhatedar_Aadhar_No = base.Columns["Khatedar_Aadhar_No"];
                this.columnBhukhand_Code = base.Columns["Bhukhand_Code"];
                this.columnGata_No = base.Columns["Gata_No"];
                this.columnBhukhandOrGata_Area = base.Columns["BhukhandOrGata_Area"];
                this.columnKhatedar_Ansh_Area = base.Columns["Khatedar_Ansh_Area"];
                this.columnAadesh = base.Columns["Aadesh"];
                this.columnTippadi = base.Columns["Tippadi"];
                this.columnBhukhandOrGata_Total_Area = base.Columns["BhukhandOrGata_Total_Area"];
                this.columnKhatedar_Ansh_Total_Area = base.Columns["Khatedar_Ansh_Total_Area"];
                this.columnTotal_Gata_Code = base.Columns["Total_Gata_Code"];
                this.columnCategory = base.Columns["Category"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnGram_Name = new global::System.Data.DataColumn("Gram_Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGram_Name);
                this.columnPargana_Name = new global::System.Data.DataColumn("Pargana_Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPargana_Name);
                this.columnTehsil_Name = new global::System.Data.DataColumn("Tehsil_Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTehsil_Name);
                this.columnDistrict_Name = new global::System.Data.DataColumn("District_Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDistrict_Name);
                this.columnFasli_Year = new global::System.Data.DataColumn("Fasli_Year", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFasli_Year);
                this.columnBhag = new global::System.Data.DataColumn("Bhag", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBhag);
                this.columnKhata_No = new global::System.Data.DataColumn("Khata_No", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKhata_No);
                this.columnKhatedar_Owner = new global::System.Data.DataColumn("Khatedar_Owner", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKhatedar_Owner);
                this.columnKhatedar_Name = new global::System.Data.DataColumn("Khatedar_Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKhatedar_Name);
                this.columnKhatedar_Father_Name = new global::System.Data.DataColumn("Khatedar_Father_Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKhatedar_Father_Name);
                this.columnKhatedar_Living_Place = new global::System.Data.DataColumn("Khatedar_Living_Place", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKhatedar_Living_Place);
                this.columnKhatedar_Aadhar_No = new global::System.Data.DataColumn("Khatedar_Aadhar_No", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKhatedar_Aadhar_No);
                this.columnBhukhand_Code = new global::System.Data.DataColumn("Bhukhand_Code", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBhukhand_Code);
                this.columnGata_No = new global::System.Data.DataColumn("Gata_No", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGata_No);
                this.columnBhukhandOrGata_Area = new global::System.Data.DataColumn("BhukhandOrGata_Area", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBhukhandOrGata_Area);
                this.columnKhatedar_Ansh_Area = new global::System.Data.DataColumn("Khatedar_Ansh_Area", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKhatedar_Ansh_Area);
                this.columnAadesh = new global::System.Data.DataColumn("Aadesh", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAadesh);
                this.columnTippadi = new global::System.Data.DataColumn("Tippadi", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTippadi);
                this.columnBhukhandOrGata_Total_Area = new global::System.Data.DataColumn("BhukhandOrGata_Total_Area", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBhukhandOrGata_Total_Area);
                this.columnKhatedar_Ansh_Total_Area = new global::System.Data.DataColumn("Khatedar_Ansh_Total_Area", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKhatedar_Ansh_Total_Area);
                this.columnTotal_Gata_Code = new global::System.Data.DataColumn("Total_Gata_Code", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTotal_Gata_Code);
                this.columnCategory = new global::System.Data.DataColumn("Category", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCategory);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAnshAgentScrappedDataRow NewdsAnshAgentScrappedDataRow() {
                return ((dsAnshAgentScrappedDataRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dsAnshAgentScrappedDataRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dsAnshAgentScrappedDataRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dsAnshAgentScrappedDataRowChanged != null)) {
                    this.dsAnshAgentScrappedDataRowChanged(this, new dsAnshAgentScrappedDataRowChangeEvent(((dsAnshAgentScrappedDataRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dsAnshAgentScrappedDataRowChanging != null)) {
                    this.dsAnshAgentScrappedDataRowChanging(this, new dsAnshAgentScrappedDataRowChangeEvent(((dsAnshAgentScrappedDataRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dsAnshAgentScrappedDataRowDeleted != null)) {
                    this.dsAnshAgentScrappedDataRowDeleted(this, new dsAnshAgentScrappedDataRowChangeEvent(((dsAnshAgentScrappedDataRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dsAnshAgentScrappedDataRowDeleting != null)) {
                    this.dsAnshAgentScrappedDataRowDeleting(this, new dsAnshAgentScrappedDataRowChangeEvent(((dsAnshAgentScrappedDataRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovedsAnshAgentScrappedDataRow(dsAnshAgentScrappedDataRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSet1 ds = new DataSet1();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dsAnshAgentScrappedDataDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dsAnshAgentScrappedDataRow : global::System.Data.DataRow {
            
            private dsAnshAgentScrappedDataDataTable tabledsAnshAgentScrappedData;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsAnshAgentScrappedDataRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledsAnshAgentScrappedData = ((dsAnshAgentScrappedDataDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Gram_Name {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Gram_NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Gram_Name\' in table \'dsAnshAgentScrappedData\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Gram_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Pargana_Name {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Pargana_NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Pargana_Name\' in table \'dsAnshAgentScrappedData\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Pargana_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Tehsil_Name {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Tehsil_NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Tehsil_Name\' in table \'dsAnshAgentScrappedData\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Tehsil_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string District_Name {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.District_NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'District_Name\' in table \'dsAnshAgentScrappedData\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.District_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Fasli_Year {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Fasli_YearColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Fasli_Year\' in table \'dsAnshAgentScrappedData\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Fasli_YearColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Bhag {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.BhagColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Bhag\' in table \'dsAnshAgentScrappedData\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.BhagColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Khata_No {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Khata_NoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Khata_No\' in table \'dsAnshAgentScrappedData\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Khata_NoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Khatedar_Owner {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Khatedar_OwnerColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Khatedar_Owner\' in table \'dsAnshAgentScrappedData\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Khatedar_OwnerColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Khatedar_Name {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Khatedar_NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Khatedar_Name\' in table \'dsAnshAgentScrappedData\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Khatedar_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Khatedar_Father_Name {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Khatedar_Father_NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Khatedar_Father_Name\' in table \'dsAnshAgentScrappedData\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Khatedar_Father_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Khatedar_Living_Place {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Khatedar_Living_PlaceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Khatedar_Living_Place\' in table \'dsAnshAgentScrappedData\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Khatedar_Living_PlaceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Khatedar_Aadhar_No {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Khatedar_Aadhar_NoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Khatedar_Aadhar_No\' in table \'dsAnshAgentScrappedData\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Khatedar_Aadhar_NoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Bhukhand_Code {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Bhukhand_CodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Bhukhand_Code\' in table \'dsAnshAgentScrappedData\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Bhukhand_CodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Gata_No {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Gata_NoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Gata_No\' in table \'dsAnshAgentScrappedData\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Gata_NoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BhukhandOrGata_Area {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.BhukhandOrGata_AreaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BhukhandOrGata_Area\' in table \'dsAnshAgentScrappedData\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.BhukhandOrGata_AreaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Khatedar_Ansh_Area {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Khatedar_Ansh_AreaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Khatedar_Ansh_Area\' in table \'dsAnshAgentScrappedData\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Khatedar_Ansh_AreaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Aadesh {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.AadeshColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Aadesh\' in table \'dsAnshAgentScrappedData\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.AadeshColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Tippadi {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.TippadiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Tippadi\' in table \'dsAnshAgentScrappedData\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.TippadiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BhukhandOrGata_Total_Area {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.BhukhandOrGata_Total_AreaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BhukhandOrGata_Total_Area\' in table \'dsAnshAgentScrappedDat" +
                                "a\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.BhukhandOrGata_Total_AreaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Khatedar_Ansh_Total_Area {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Khatedar_Ansh_Total_AreaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Khatedar_Ansh_Total_Area\' in table \'dsAnshAgentScrappedData" +
                                "\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Khatedar_Ansh_Total_AreaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Total_Gata_Code {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.Total_Gata_CodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Total_Gata_Code\' in table \'dsAnshAgentScrappedData\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.Total_Gata_CodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Category {
                get {
                    try {
                        return ((string)(this[this.tabledsAnshAgentScrappedData.CategoryColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Category\' in table \'dsAnshAgentScrappedData\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAnshAgentScrappedData.CategoryColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsGram_NameNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Gram_NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetGram_NameNull() {
                this[this.tabledsAnshAgentScrappedData.Gram_NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPargana_NameNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Pargana_NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPargana_NameNull() {
                this[this.tabledsAnshAgentScrappedData.Pargana_NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTehsil_NameNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Tehsil_NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTehsil_NameNull() {
                this[this.tabledsAnshAgentScrappedData.Tehsil_NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDistrict_NameNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.District_NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDistrict_NameNull() {
                this[this.tabledsAnshAgentScrappedData.District_NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFasli_YearNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Fasli_YearColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFasli_YearNull() {
                this[this.tabledsAnshAgentScrappedData.Fasli_YearColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBhagNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.BhagColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBhagNull() {
                this[this.tabledsAnshAgentScrappedData.BhagColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKhata_NoNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Khata_NoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKhata_NoNull() {
                this[this.tabledsAnshAgentScrappedData.Khata_NoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKhatedar_OwnerNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Khatedar_OwnerColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKhatedar_OwnerNull() {
                this[this.tabledsAnshAgentScrappedData.Khatedar_OwnerColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKhatedar_NameNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Khatedar_NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKhatedar_NameNull() {
                this[this.tabledsAnshAgentScrappedData.Khatedar_NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKhatedar_Father_NameNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Khatedar_Father_NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKhatedar_Father_NameNull() {
                this[this.tabledsAnshAgentScrappedData.Khatedar_Father_NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKhatedar_Living_PlaceNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Khatedar_Living_PlaceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKhatedar_Living_PlaceNull() {
                this[this.tabledsAnshAgentScrappedData.Khatedar_Living_PlaceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKhatedar_Aadhar_NoNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Khatedar_Aadhar_NoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKhatedar_Aadhar_NoNull() {
                this[this.tabledsAnshAgentScrappedData.Khatedar_Aadhar_NoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBhukhand_CodeNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Bhukhand_CodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBhukhand_CodeNull() {
                this[this.tabledsAnshAgentScrappedData.Bhukhand_CodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsGata_NoNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Gata_NoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetGata_NoNull() {
                this[this.tabledsAnshAgentScrappedData.Gata_NoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBhukhandOrGata_AreaNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.BhukhandOrGata_AreaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBhukhandOrGata_AreaNull() {
                this[this.tabledsAnshAgentScrappedData.BhukhandOrGata_AreaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKhatedar_Ansh_AreaNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Khatedar_Ansh_AreaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKhatedar_Ansh_AreaNull() {
                this[this.tabledsAnshAgentScrappedData.Khatedar_Ansh_AreaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAadeshNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.AadeshColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAadeshNull() {
                this[this.tabledsAnshAgentScrappedData.AadeshColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTippadiNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.TippadiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTippadiNull() {
                this[this.tabledsAnshAgentScrappedData.TippadiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBhukhandOrGata_Total_AreaNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.BhukhandOrGata_Total_AreaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBhukhandOrGata_Total_AreaNull() {
                this[this.tabledsAnshAgentScrappedData.BhukhandOrGata_Total_AreaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKhatedar_Ansh_Total_AreaNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Khatedar_Ansh_Total_AreaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKhatedar_Ansh_Total_AreaNull() {
                this[this.tabledsAnshAgentScrappedData.Khatedar_Ansh_Total_AreaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTotal_Gata_CodeNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.Total_Gata_CodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTotal_Gata_CodeNull() {
                this[this.tabledsAnshAgentScrappedData.Total_Gata_CodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCategoryNull() {
                return this.IsNull(this.tabledsAnshAgentScrappedData.CategoryColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCategoryNull() {
                this[this.tabledsAnshAgentScrappedData.CategoryColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class dsAnshAgentScrappedDataRowChangeEvent : global::System.EventArgs {
            
            private dsAnshAgentScrappedDataRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAnshAgentScrappedDataRowChangeEvent(dsAnshAgentScrappedDataRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAnshAgentScrappedDataRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591